config/routes.rb
Rails.application.routes.draw do
  #route file gets read in order so it's important to
  #put new route above show route
  root 'sessions#welcome'
  #get '/ratings/best,' to 'ratings#best', as: 'best_rating'
  resources :ratings, only: [:new, :create, :show, :index]
  resources :books, only: [:new, :create, :show, :index] do
    resources :ratings, shallow: true
  end
  resources :users
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'sort' => 'books#sort'
  #new will render the form
  get '/login', to: 'sessions#new'
  get '/best', to:'books#best'
  #get '/best', to 'books#best'
  #create will process the form once you submit it
  get '/logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post '/', to: 'sessions#create'
  post '/ratings/new', to: 'ratings#index'

  #get '/sessions', to: 'sessions#home' 
  
  #post '/ratings/best,' to 'ratings#best', as: 'best_rating'
  #get '/users/:id', to: 'user#show', as: 'user'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#'/users/chrissy_t/shoes'
#'/users/2/shoes'

end

#which one of these qualifies as a nested route?

app/models/book.rb
class Book < ApplicationRecord
  #validations exist in the model 
validates :title, presence: true, uniqueness: true
validates :author, presence: true
has_many :ratings
has_many :users, through: :ratings
accepts_nested_attributes_for :ratings


def title_and_author
  "#{self.title} - #{self.author}"
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_logged_in

def index
  #@books = Book.order(:title)
  @books = Book.all
  #@rating = book.rating
  #not a button will this be ok?
end

def sort
  @books = Book.order(:title)
end

def new
  @book = Book.new
  #@book.ratings.build
end

def edit
  @book = Book.find(params[:id])
end

def update
  @book = Book.find(params[:book][:title])
  @book.update(title:params[:book][:title], author:params[:book][:author])
  redirect_to book_path(@book)

end

def create
  
  #@book = Book.new(book_params)
  #@book = Book.new(title:params[:book][:title], author:params[:book][:author])
    @book = current_user.books.build(book_params)
    #try to save it - validations are run on save
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
  end
end
  
def show
  @book = Book.find(params[:id])
end

def destroy 
  @book.destroy
  redirect_to root_path
end 



private

def book_params
  params.require(:book).permit(:title, :author)
end

def require_logged_in
  return redirect_to root_path unless logged_in?
end
#def best
#book with best rating

end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/best.html.erb
<%= display_header(@book) %>
<% @ratings.each do |rating| %> 
  
<br>Title: <%= rating.book.title %> <br>
Book ID: <%=rating.book.id %>
<br> 
Rating: 
<%= rating.number %>  
<br>
Additional Comment:  <%= rating.comment %> <br>
Who left this rating: <%= rating.user.username %> <br>
<%= button_to "Delete this rating", rating, :method => :delete %>
<%= link_to("Edit Rating", edit_rating_path(rating)) %> <br>

app/views/books/edit.html.erb
<%= form_for (@book) do |f| %>
  <div class="field">
  <%=f.label :title %>
  <%=f.text_field :title %>
  </div>

  <div class="field">
  <%=f.label :author %>
  <%=f.text_field :author %>
  </div>


  <div>
  <%=f.submit %>
  </div>
  <% end %>
  

app/views/books/index.html.erb
<h1> Book Index </h1>

 <% @books.each do |book| %>
 <%= link_to(book.title, book_ratings_path(book.id)) %>
 
<br>

<% end %> 
<br>

<%= link_to("Create New Book", new_book_path) %>
<br>
<%= link_to '<button type="button">Sort Alphabetically</button>'.html_safe, sort_path %>

app/views/books/new.html.erb
<h1> New Book </h1>


  <%= form_for(@book) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :author %>
    <%= f.text_field :author %>
    

<%= f.submit %>
    <% end %> 

app/views/books/show.html.erb
Book Show Page <br>

 Title: <%= @book.title %> <br>
 Author: <%= @book.author %> <br>
 <%= link_to("View all current ratings for #{@book.title}", book_ratings_path(@book.id))  %> <br>
 <%= link_to("Make a new rating for #{@book.title} or another book", new_book_rating_path(@book.id))  %>

app/views/books/sort.html.erb
<h1> Book Index </h1>

 <% @books.each do |book| %>
  
 <%= link_to(book.title, book_ratings_path(book.id)) %>
 
<br>

<% end %> 
<br>
<%= link_to("Create New Book", new_book_path) %>