config/routes.rb
Rails.application.routes.draw do
  #route file gets read in order so it's important to
  #put new route above show route
  root 'sessions#welcome'
  #get '/ratings/best,' to 'ratings#best', as: 'best_rating'
  resources :ratings, only: [:new, :create, :show, :index]
  resources :books, only: [:new, :create, :show, :index] do
    resources :ratings, shallow: true
  end
  resources :users
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'sort' => 'books#sort'
  #new will render the form
  get '/login', to: 'sessions#new'
  get '/best', to:'books#best'
  #get '/best', to 'books#best'
  #create will process the form once you submit it
  get '/logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post '/', to: 'sessions#create'
  post '/ratings/new', to: 'ratings#index'

  #get '/sessions', to: 'sessions#home' 
  
  #post '/ratings/best,' to 'ratings#best', as: 'best_rating'
  #get '/users/:id', to: 'user#show', as: 'user'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#'/users/chrissy_t/shoes'
#'/users/2/shoes'

end

#which one of these qualifies as a nested route?

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  </head>
  <body>

  
  <%= link_to(" All Books", books_path) %>
  <%= link_to(" All Ratings", book_ratings_path(:book_id)) %>
  <%= button_to "Log in with Google", '/auth/google_oauth2'  %>
  <%= link_to("Signup", signup_path) %>
  <%= link_to("Logout", logout_path) %>
 

  <hr>
  
  <% if flash[:message] %>
  <div class="field_with_errors"> 
  <%= flash[:message] %></div>
  <% end %>

    <%= yield %>
  </body>  
</html>